export const OPENAI_API_KEY = OPENAI_API_KEY;
export const OPENAI_BASE_URL = OPENAI_BASE_URL || 'https://api.openai.com/v1';
export const OPENAI_MODELS = OPENAI_MODELS ? OPENAI_MODELS.split(',').map(model => model.trim()) : [];
export const DEFAULT_MODEL = OPENAI_MODELS ? OPENAI_MODELS.split(',').map(model => model.trim())[0] : null;
export const AZURE_OPENAI_API_KEY = AZURE_OPENAI_API_KEY;
export const AZURE_OPENAI_ENDPOINT = AZURE_OPENAI_ENDPOINT;
export const AZURE_OPENAI_MODELS = AZURE_OPENAI_MODELS ? AZURE_OPENAI_MODELS.split(',').map(model => model.trim()) : [];
export const TELEGRAM_BOT_TOKEN = TELEGRAM_BOT_TOKEN;
export const WHITELISTED_USERS = WHITELISTED_USERS ? WHITELISTED_USERS.split(',').map(id => parseInt(id.trim())) : [];
export const DALL_E_MODEL = DALL_E_MODEL || "dall-e-3";
export const UPSTASH_REDIS_REST_URL = UPSTASH_REDIS_REST_URL;
export const UPSTASH_REDIS_REST_TOKEN = UPSTASH_REST_TOKEN;
export const SYSTEM_INIT_MESSAGE = SYSTEM_INIT_MESSAGE || 'You are a helpful assistant.';
export const SYSTEM_INIT_MESSAGE_ROLE = SYSTEM_INIT_MESSAGE_ROLE || 'system';
export const GEMINI_API_KEY = GEMINI_API_KEY;
export const GOOGLE_MODELS = GOOGLE_MODELS ? GOOGLE_MODELS.split(',').map(model => model.trim()) : [];
export const GEMINI_ENDPOINT = GEMINI_ENDPOINT || 'https://generativelanguage.googleapis.com/v1beta/models';
export const GROQ_API_KEY = GROQ_API_KEY;
export const GROQ_MODELS = GROQ_MODELS ? GROQ_MODELS.split(',').map(model => model.trim()) : [];
export const MAX_HISTORY_LENGTH = parseInt(MAX_HISTORY_LENGTH) || 50;
export const CLAUDE_API_KEY = CLAUDE_API_KEY;
export const CLAUDE_MODELS = CLAUDE_MODELS ? CLAUDE_MODELS.split(',').map(model => model.trim()) : [];
export const CLAUDE_ENDPOINT = CLAUDE_ENDPOINT || 'https://api.anthropic.com/v1/chat/completions';